function constructorArquero(listaCaracteristicas) {
    personaje = new Arquero(listaCaracteristicas[0]['nombre'], parseInt(listaCaracteristicas[0]['fuerza']), parseInt(listaCaracteristicas[0]['armadura']), parseInt(listaCaracteristicas[0]['nivel']), parseInt(listaCaracteristicas[0]['vidaActual']), parseInt(listaCaracteristicas[0]['vidaMaxima']), parseInt(listaCaracteristicas[0]['estaminaActual']), parseInt(listaCaracteristicas[0]['estaminaMaxima']), parseInt(listaCaracteristicas[0]['puntosExperiencia']), parseInt(listaCaracteristicas[0]['quemado']), parseInt(listaCaracteristicas[0]['envenenado']), parseInt(listaCaracteristicas[0]['confundido']), parseInt(listaCaracteristicas[0]['heridoLeve']), parseInt(listaCaracteristicas[0]['heridoGrave']), parseInt(listaCaracteristicas[0]['punteria']));

    personaje.asignarObjetos(parseInt(listaCaracteristicas['arma']['arco']['desgaste']), parseInt(listaCaracteristicas['arma']['flecha']['cantidad']), parseInt(listaCaracteristicas['arma']['nunchakus']['desgaste']), parseInt(listaCaracteristicas['curacion']['curacionSimple']['cantidad']), parseInt(listaCaracteristicas['curacion']['superCuracion']['cantidad']), parseInt(listaCaracteristicas['curacion']['curacionCompleta']['cantidad']), parseInt(listaCaracteristicas['estamina']['restaurarEstamina']['cantidad']), parseInt(listaCaracteristicas['estamina']['restaurarMuchaEstamina']['cantidad']), parseInt(listaCaracteristicas['estamina']['restaurarTodaEstamina']['cantidad']));
    return personaje;
}

function constructorCaballero(listaCaracteristicas) {
    personaje = new Caballero(listaCaracteristicas[0]['nombre'], parseInt(listaCaracteristicas[0]['fuerza']), parseInt(listaCaracteristicas[0]['armadura']), parseInt(listaCaracteristicas[0]['nivel']), parseInt(listaCaracteristicas[0]['vidaActual']), parseInt(listaCaracteristicas[0]['vidaMaxima']), parseInt(listaCaracteristicas[0]['estaminaActual']), parseInt(listaCaracteristicas[0]['estaminaMaxima']), parseInt(listaCaracteristicas[0]['puntosExperiencia']), parseInt(listaCaracteristicas[0]['quemado']), parseInt(listaCaracteristicas[0]['envenenado']), parseInt(listaCaracteristicas[0]['confundido']), parseInt(listaCaracteristicas[0]['heridoLeve']), parseInt(listaCaracteristicas[0]['heridoGrave']));

    personaje.asignarObjetos(parseInt(listaCaracteristicas['arma']['espada']['desgaste']), parseInt(listaCaracteristicas['arma']['mazo']['desgaste']), parseInt(listaCaracteristicas['curacion']['curacionSimple']['cantidad']), parseInt(listaCaracteristicas['curacion']['superCuracion']['cantidad']), parseInt(listaCaracteristicas['curacion']['curacionCompleta']['cantidad']), parseInt(listaCaracteristicas['estamina']['restaurarEstamina']['cantidad']), parseInt(listaCaracteristicas['estamina']['restaurarMuchaEstamina']['cantidad']), parseInt(listaCaracteristicas['estamina']['restaurarTodaEstamina']['cantidad']));
    return personaje;
}

function constructorHechicero(listaCaracteristicas) {
    personaje = new Hechicero(listaCaracteristicas[0]['nombre'], parseInt(listaCaracteristicas[0]['fuerza']), parseInt(listaCaracteristicas[0]['armadura']), parseInt(listaCaracteristicas[0]['nivel']), parseInt(listaCaracteristicas[0]['vidaActual']), parseInt(listaCaracteristicas[0]['vidaMaxima']), parseInt(listaCaracteristicas[0]['estaminaActual']), parseInt(listaCaracteristicas[0]['estaminaMaxima']), parseInt(listaCaracteristicas[0]['puntosExperiencia']), parseInt(listaCaracteristicas[0]['quemado']), parseInt(listaCaracteristicas[0]['envenenado']), parseInt(listaCaracteristicas[0]['confundido']), parseInt(listaCaracteristicas[0]['heridoLeve']), parseInt(listaCaracteristicas[0]['heridoGrave']), parseInt(listaCaracteristicas[0]['inteligencia']), parseInt(listaCaracteristicas[0]['fuego']), parseInt(listaCaracteristicas[0]['veneno']), parseInt(listaCaracteristicas[0]['enigmatico']), parseInt(listaCaracteristicas[0]['pinchos']), parseInt(listaCaracteristicas[0]['sombra']));

    personaje.asignarObjetos(parseInt(listaCaracteristicas['arma']['vara']['desgaste']), parseInt(listaCaracteristicas['curacion']['curacionSimple']['cantidad']), parseInt(listaCaracteristicas['curacion']['superCuracion']['cantidad']), parseInt(listaCaracteristicas['curacion']['curacionCompleta']['cantidad']), parseInt(listaCaracteristicas['estamina']['restaurarEstamina']['cantidad']), parseInt(listaCaracteristicas['estamina']['restaurarMuchaEstamina']['cantidad']), parseInt(listaCaracteristicas['estamina']['restaurarTodaEstamina']['cantidad']));
    return personaje;
}

function constructorDruida(listaCaracteristicas) {
    personaje = new Druida(listaCaracteristicas[0]['nombre'], parseInt(listaCaracteristicas[0]['fuerza']), parseInt(listaCaracteristicas[0]['armadura']), parseInt(listaCaracteristicas[0]['nivel']), parseInt(listaCaracteristicas[0]['vidaActual']), parseInt(listaCaracteristicas[0]['vidaMaxima']), parseInt(listaCaracteristicas[0]['estaminaActual']), parseInt(listaCaracteristicas[0]['estaminaMaxima']), parseInt(listaCaracteristicas[0]['puntosExperiencia']), parseInt(listaCaracteristicas[0]['quemado']), parseInt(listaCaracteristicas[0]['envenenado']), parseInt(listaCaracteristicas[0]['confundido']), parseInt(listaCaracteristicas[0]['heridoLeve']), parseInt(listaCaracteristicas[0]['heridoGrave']), parseInt(listaCaracteristicas[0]['inteligencia']), parseInt(listaCaracteristicas[0]['oso']), parseInt(listaCaracteristicas[0]['serpiente']), parseInt(listaCaracteristicas[0]['zorro']), parseInt(listaCaracteristicas[0]['aguila']));

    personaje.asignarObjetos(parseInt(listaCaracteristicas['arma']['daga']['desgaste']), parseInt(listaCaracteristicas['curacion']['curacionSimple']['cantidad']), parseInt(listaCaracteristicas['curacion']['superCuracion']['cantidad']), parseInt(listaCaracteristicas['curacion']['curacionCompleta']['cantidad']), parseInt(listaCaracteristicas['estamina']['restaurarEstamina']['cantidad']), parseInt(listaCaracteristicas['estamina']['restaurarMuchaEstamina']['cantidad']), parseInt(listaCaracteristicas['estamina']['restaurarTodaEstamina']['cantidad']));
    return personaje;
}